### ISSUE TITLE
How can I use your pre-trained models to make inferences with my network data?

### ISSUE THREAD

**Issue by shintarok111** [NetworkScienceLab/GDM#2]
Hi, Marco, 

Thank you for the nice work about network dismantling. 

I read your instructions and was able to reproduce your results at least partialy, but I could not find what to do with my own data to infer dismanting . 
How can I use your pre-trained models to make inferences with my own network data?
I'd like to know about the API a little bit more. 

I would be happy if you could help me. 
Thank you 

shin111

**Comment by eMarco** [comment]
Dear shin111,

You can dismantle your own networks by following sections [Dataset generation](https://github.com/NetworkScienceLab/GDM#dataset-generation) and then [Running a grid search](https://github.com/NetworkScienceLab/GDM#running-a-grid-search).
If you also wish to run the reinsertion phase, you should also check section [Reinsert nodes](https://github.com/NetworkScienceLab/GDM#reinsert-nodes) out.


Best,
Marco

**Comment by Oliver-0423** [comment]
Why is it necessary to “run a grid search”? Shouldn't there be a final trained model ready for testing? Shouldn't the grid search portion be completed during the training phase?
