### ISSUE TITLE
Questioning the test results of the GDM model

### ISSUE THREAD

**Issue by Hongliaaa** [NetworkScienceLab/GDM#4]
Hello! Your work on Machine learning dismantling and early-warning signals of disintegration in complex systems is very interesting. we have some questions about this work. In reproducing this work, we found the node removal order of the test network arenas-meta from this file "out/df/synth_train_NEW/t_0.18/T_0.1/GAT_Model.csv" which contains the label of each node and the predicted values of GDM model. However, according to the node removal order, the LCC result is very different from the result of your appendix material, what is the reason for this? We are looking forward to hearing from you! Thanks!

**Comment by eMarco** [comment]
Hi, every detail of the dismantling process is discussed in the paper.
There may various reasons the results may be different from the ones reported, but my guess is that - assuming you're using the right versions of the libraries - you're not using the LCC dismantler provided with the code, which basically removes the nodes only if they belong to the LCC.

Regards,
Marco
